baseURL = "/"
languageCode = "en-us"
title = "Quorum Execute Release Notes"
disableKinds = ["taxonomy", "term"]

[params]
productName = "Execute"

[outputFormats]
  [outputFormats.Since]
    mediaType = "text/html"
    baseName = "since"
    isHTML = true
  
[outputs]
  home = ["HTML"]
  page = ["HTML", "since"]
  