baseURL = ""
languageCode = "en-us"
title = "Quorum Execute Release Notes"
disableKinds = ["taxonomy", "term"]

[params]
productName = "Execute"

[outputFormats]
  [outputFormats.Since]
    mediaType = "text/html"
    baseName = "since"
    isHTML = true
  [outputFormats.current]
    MediaType = "text/plain"
    BaseName = "current"
    IsPlainText = true
    NotAlternative = true
  
[outputs]
  home = ["HTML", "current"]
  page = ["HTML", "since"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/index.html"
    weight = 1

  [[menu.main]]
    name = "All Changes"
    url = "/everything/index.html"
    weight = 2 