'on':
  push:
    branches:
      - staging

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "deploy"
  cancel-in-progress: false

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Node setup
        uses: actions/setup-node@v4
      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.6.0
        with:
            hugo-version: '0.140.2' # optional, default is latest
            extended: true # optional, default is false
      - name: NPM
        run: npm install
      - name: Build
        run: hugo -b https://release-notes.deliveryraptor.net/ -D -F
        env:
          HUGO_SHOW_DEVOPS_LINKS: true
          HUGO_SHOW_DOWNLOAD_LINKS: true
      - name: Upload to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PAGES_PROJECT_NAME }}
          directory: ./public